export const mockData = {
    data: {
        products: [
            {
                brand: "L'ORÉAL PARIS",
                caption: 'serum do twarzy, regenerujące, na noc',
                unit: '30 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 390628,
                rossnetId: 524693,
                eanNumber: ['3600524012601'],
                navigateUrl:
                    '/Produkt/Serum/LOreal-Paris-Age-Perfect-Cell-Renew-serum-do-twarzy-regenerujace-na-noc-30-ml,390628,9225',
                name: 'Age Perfect Cell Renew',
                price: 97.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 326,63 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/390628_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/390628_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/390628_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/390628_1280_720.png',
                        type: 2,
                        alt: "L'ORÉAL PARIS,serum do twarzy, regenerujące, na noc,kompozycja-1",
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/390628_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/390628_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/390628_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/390628_1280_720.png',
                        type: 1,
                        alt: "L'ORÉAL PARIS,serum do twarzy, regenerujące, na noc,przód",
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/390628_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/390628_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/390628_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/390628_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,serum do twarzy, regenerujące, na noc,tył",
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/390628_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/390628_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/390628_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/390628_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,serum do twarzy, regenerujące, na noc,lewa",
                        side: 'Left',
                    },
                    {
                        id: 6,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_mini/390628_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_medium/390628_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_small/390628_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_large/390628_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,serum do twarzy, regenerujące, na noc,od-dostawcy",
                        side: 'FromSupplier',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Serum',
            },
            {
                brand: "L'ORÉAL PARIS",
                caption: 'krem pod oczy, rozświetlający',
                unit: '15 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 390630,
                rossnetId: 524695,
                eanNumber: ['3600524013448'],
                navigateUrl:
                    '/Produkt/Kremy-pod-oczy/LOreal-Paris-Age-Perfect-Cell-Renew-krem-pod-oczy-rozswietlajacy-15-ml,390630,9224',
                name: 'Age Perfect Cell Renew',
                price: 94.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 633,27 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/390630_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/390630_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/390630_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/390630_1280_720.png',
                        type: 2,
                        alt: "L'ORÉAL PARIS,krem pod oczy, rozświetlający,kompozycja-1",
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/390630_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/390630_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/390630_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/390630_1280_720.png',
                        type: 1,
                        alt: "L'ORÉAL PARIS,krem pod oczy, rozświetlający,przód",
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/390630_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/390630_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/390630_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/390630_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem pod oczy, rozświetlający,tył",
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/390630_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/390630_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/390630_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/390630_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem pod oczy, rozświetlający,lewa",
                        side: 'Left',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy pod oczy',
            },
            {
                brand: "L'ORÉAL PARIS",
                caption: 'krem do twarzy, rewitalizujący, SPF 30, na dzień',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 390632,
                rossnetId: 524697,
                eanNumber: ['3600524013370'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/LOreal-Paris-Age-Perfect-Cell-Renew-krem-do-twarzy-rewitalizujacy-SPF-30-na-dzien-50-ml,390632,9223',
                name: 'Age Perfect Cell Renew',
                price: 91.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 183,98 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/390632_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/390632_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/390632_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/390632_1280_720.png',
                        type: 2,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, SPF 30, na dzień,kompozycja-1",
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/390632_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/390632_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/390632_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/390632_1280_720.png',
                        type: 1,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, SPF 30, na dzień,przód",
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/390632_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/390632_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/390632_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/390632_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, SPF 30, na dzień,tył",
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/390632_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/390632_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/390632_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/390632_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, SPF 30, na dzień,lewa",
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/390632_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/390632_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/390632_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/390632_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, SPF 30, na dzień,prawa",
                        side: 'Right',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: "L'ORÉAL PARIS",
                caption: 'krem do twarzy, rewitalizujący, na dzień',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 390629,
                rossnetId: 524694,
                eanNumber: ['3600524013462'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/LOreal-Paris-Age-Perfect-Cell-Renew-krem-do-twarzy-rewitalizujacy-na-dzien-50-ml,390629,9223',
                name: 'Age Perfect Cell Renew',
                price: 91.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 183,98 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/390629_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/390629_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/390629_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/390629_1280_720.png',
                        type: 1,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, na dzień,przód",
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/390629_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/390629_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/390629_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/390629_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, na dzień,tył",
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/390629_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/390629_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/390629_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/390629_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, na dzień,lewa",
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/390629_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/390629_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/390629_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/390629_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, na dzień,prawa",
                        side: 'Right',
                    },
                    {
                        id: 6,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_mini/390629_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_medium/390629_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_small/390629_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_large/390629_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, rewitalizujący, na dzień,od-dostawcy",
                        side: 'FromSupplier',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: "L'ORÉAL PARIS",
                caption: 'krem do twarzy, regenerujący, na noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 390631,
                rossnetId: 524696,
                eanNumber: ['3600524066475', '3600524013455'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/LOreal-Paris-Age-Perfect-Cell-Renew-krem-do-twarzy-regenerujacy-na-noc-50-ml,390631,9223',
                name: 'Age Perfect Cell Renew',
                price: 91.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 183,98 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/390631_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/390631_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/390631_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/390631_1280_720.png',
                        type: 1,
                        alt: "L'ORÉAL PARIS,krem do twarzy, regenerujący, na noc,przód",
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/390631_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/390631_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/390631_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/390631_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, regenerujący, na noc,tył",
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/390631_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/390631_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/390631_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/390631_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, regenerujący, na noc,lewa",
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/390631_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/390631_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/390631_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/390631_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, regenerujący, na noc,prawa",
                        side: 'Right',
                    },
                    {
                        id: 6,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_mini/390631_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_medium/390631_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_small/390631_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_5_large/390631_1280_720.png',
                        type: 0,
                        alt: "L'ORÉAL PARIS,krem do twarzy, regenerujący, na noc,od-dostawcy",
                        side: 'FromSupplier',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'CHRISTIAN LAURENT',
                caption:
                    'serum do twarzy, superskoncentrowane, diamentowe, napinające',
                unit: '30 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 317887,
                rossnetId: 452709,
                eanNumber: ['5901761986372'],
                navigateUrl:
                    '/Produkt/Serum/Christian-Laurent-Edition-de-Luxe-serum-do-twarzy-superskoncentrowane-diamentowe-napinajace-30-,317887,9225',
                name: 'Edition de Luxe ',
                price: 76.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 256,63 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/317887_1280_720.png',
                        type: 2,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/317887_1280_720.png',
                        type: 1,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/317887_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/317887_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/317887_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/317887_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/317887_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/317887_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/317887_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,serum do twarzy, superskoncentrowane, diamentowe, napinające,dół',
                        side: 'Bottom',
                    },
                ],
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Serum',
            },
            {
                brand: 'CHRISTIAN LAURENT',
                caption: 'krem do twarzy, diamentowy, dzień/noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 317886,
                rossnetId: 452708,
                eanNumber: ['5901761989168'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/Christian-Laurent-Edition-de-Luxe-krem-do-twarzy-diamentowy-dzien-noc-50-ml,317886,9223',
                name: 'Edition de Luxe ',
                price: 81.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 163,98 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/317886_1280_720.png',
                        type: 2,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/317886_1280_720.png',
                        type: 1,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/317886_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/317886_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/317886_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/317886_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/317886_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/317886_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/317886_1280_720.png',
                        type: 0,
                        alt: 'CHRISTIAN LAURENT,krem do twarzy, diamentowy, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'rossmann',
                    redirectUrl: '/produkty?Statuses=rossmann',
                },
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc',
                unit: '60 g',
                averageRating: 0,
                totalReviews: 0,
                id: 409859,
                rossnetId: 544144,
                eanNumber: ['5902046768584'],
                navigateUrl:
                    '/Produkt/Serum/Dermika-Luxury-Caviar-serum-do-twarzy-kawiorowe-przeciwzmarszczkowe-w-kapsulkach-dzie-60-g,409859,9225',
                name: 'Luxury Caviar ',
                oldPrice: 96.99,
                price: 59.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 g = 99,98 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/409859_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/409859_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/409859_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/409859_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/409859_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/409859_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/409859_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/409859_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/409859_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, kawiorowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Serum',
            },
            {
                brand: 'DERMIKA',
                caption: 'krem pod oczy, kawiorowy, intensywnie regenerujący',
                unit: '15 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381354,
                rossnetId: 515671,
                eanNumber: ['5902046767105'],
                navigateUrl:
                    '/Produkt/Kremy-pod-oczy/Dermika-Luxury-Caviar-krem-pod-oczy-kawiorowy-intensywnie-regenerujacy-15-ml,381354,9224',
                name: 'Luxury Caviar ',
                oldPrice: 52.99,
                price: 31.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 213,27 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381354_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381354_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381354_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381354_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/381354_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381354_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381354_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381354_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381354_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem pod oczy, kawiorowy, intensywnie regenerujący,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy pod oczy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381350,
                rossnetId: 515667,
                eanNumber: ['5902046767068'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/Dermika-Luxury-Caviar-krem-do-twarzy-kawiorowy-wypelniajacy-zmarszczki-50-dzien-noc-50-ml,381350,9223',
                name: 'Luxury Caviar ',
                oldPrice: 72.99,
                price: 44.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 89,98 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381350_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381350_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381350_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381350_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381350_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381350_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381350_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381350_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381350_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381350_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381350_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381350_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381350_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381350_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381350_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381350_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381350_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381350_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381350_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381350_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, wypełniający zmarszczki, 50+, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381351,
                rossnetId: 515668,
                eanNumber: ['5902046767075'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/Dermika-Luxury-Caviar-krem-do-twarzy-kawiorowy-aktywnie-regenerujacy-60-dzien-noc-50-ml,381351,9223',
                name: 'Luxury Caviar ',
                oldPrice: 72.99,
                price: 44.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 89,98 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381351_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381351_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381351_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381351_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/381351_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381351_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381351_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381351_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381351_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, aktywnie regenerujący, 60+, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381352,
                rossnetId: 515669,
                eanNumber: ['5902046767082'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/Dermika-Luxury-Caviar-krem-do-twarzy-kawiorowy-odbudowujacy-70-dzien-noc-50-ml,381352,9223',
                name: 'Luxury Caviar ',
                oldPrice: 72.99,
                price: 44.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 89,98 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381352_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381352_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381352_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381352_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/381352_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381352_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381352_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381352_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381352_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem do twarzy, kawiorowy, odbudowujący, 70+, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc',
                unit: '50 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381353,
                rossnetId: 515670,
                eanNumber: ['5902046767099'],
                navigateUrl:
                    '/Produkt/Kremy-do-twarzy/Dermika-Luxury-Caviar-krem-elixir-do-twarzy-kawiorowy-przeciwzmarszczkowy-na-noc-50-ml,381353,9223',
                name: 'Luxury Caviar ',
                oldPrice: 72.99,
                price: 44.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 89,98 zł',
                cmpType: 'regular',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381353_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381353_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381353_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381353_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/381353_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381353_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381353_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381353_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381353_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-elixir do twarzy, kawiorowy, przeciwzmarszczkowy, na noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'mega',
                    redirectUrl: '/produkty?Statuses=mega',
                },
                promotionFrom: '2023-11-03T00:00:00',
                promotionTo: '2023-11-15T00:00:00',
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy do twarzy',
            },
            {
                brand: 'DERMIKA',
                caption:
                    'serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc',
                unit: '60 g',
                averageRating: 0,
                totalReviews: 0,
                id: 409858,
                rossnetId: 544143,
                eanNumber: ['5902046768591'],
                navigateUrl:
                    '/Produkt/Serum/Dermika-Luxury-Ceramides-serum-do-twarzy-ceramidowe-przeciwzmarszczkowe-w-kapsulkach-dzi-60-g,409858,9225',
                name: 'Luxury Ceramides ',
                price: 96.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 g = 161,65 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/409858_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/409858_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/409858_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/409858_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/409858_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/409858_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/409858_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/409858_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/409858_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,serum do twarzy, ceramidowe, przeciwzmarszczkowe, w kapsułkach, dzień/noc,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'rossmann',
                    redirectUrl: '/produkty?Statuses=rossmann',
                },
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Serum',
            },
            {
                brand: 'DERMIKA',
                caption: 'krem-serum pod oczy, liftingujący',
                unit: '15 ml',
                averageRating: 0,
                totalReviews: 0,
                id: 381476,
                rossnetId: 515784,
                eanNumber: ['5902046767006'],
                navigateUrl:
                    '/Produkt/Kremy-pod-oczy/Dermika-Luxury-Ceramides-krem-serum-pod-oczy-liftingujacy-15-ml,381476,9224',
                name: 'Luxury Ceramides ',
                price: 51.99,
                vat: 23,
                dimensional: 0,
                pricePerUnit: '100 ml = 346,60 zł',
                pictures: [
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_7_large/381476_1280_720.png',
                        type: 2,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,kompozycja-1',
                        side: 'Compositional1',
                    },
                    {
                        id: 1,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_1_large/381476_1280_720.png',
                        type: 1,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,przód',
                        side: 'Front',
                    },
                    {
                        id: 3,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_2_large/381476_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,tył',
                        side: 'Back',
                    },
                    {
                        id: 4,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_3_large/381476_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,lewa',
                        side: 'Left',
                    },
                    {
                        id: 5,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_4_large/381476_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,prawa',
                        side: 'Right',
                    },
                    {
                        id: 9,
                        mini: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_mini/381476_55_71.png',
                        medium: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_medium/381476_360_350.png',
                        small: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_small/381476_338_190.png',
                        large: 'https://pro-fra-s3-productsassets.rossmann.pl/product_8_large/381476_1280_720.png',
                        type: 0,
                        alt: 'DERMIKA,krem-serum pod oczy, liftingujący,dół',
                        side: 'Bottom',
                    },
                ],
                promotion: {
                    type: 'rossmann',
                    redirectUrl: '/produkty?Statuses=rossmann',
                },
                hasRichContent: false,
                availability: 'available',
                category: 'Twarz-Pielęgnacja twarzy-Kremy pod oczy',
            },
        ],
        totalPages: 1681,
        totalCount: 25207,
    },
};
